[2019-03-30 23:03:45,914] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 1 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2019-03-30 23:13:45,924] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2019-03-30 23:23:45,923] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2019-03-30 23:26:23,362] WARN [Controller id=0, targetBrokerId=0] Connection to node 0 could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2019-03-30 23:29:35,155] WARN [Controller id=0, targetBrokerId=0] Connection to node 0 could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2019-03-30 23:33:45,940] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 1 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2019-03-30 23:39:56,633] WARN [Controller id=0, targetBrokerId=0] Connection to node 0 could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2019-03-30 23:43:45,917] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2019-03-30 23:53:45,924] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 1 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2019-03-30 23:59:15,621] INFO [Log partition=response_topic-0, dir=/tmp/kafka-logs] Found deletable segments with base offsets [0] due to retention time 604800000ms breach (kafka.log.Log)
[2019-03-30 23:59:15,812] INFO [ProducerStateManager partition=response_topic-0] Writing producer snapshot at offset 1 (kafka.log.ProducerStateManager)
[2019-03-30 23:59:15,875] INFO [Log partition=response_topic-0, dir=/tmp/kafka-logs] Rolled new log segment at offset 1 in 187 ms. (kafka.log.Log)
[2019-03-30 23:59:15,883] INFO [Log partition=response_topic-0, dir=/tmp/kafka-logs] Scheduling log segment [baseOffset 0, size 345] for deletion. (kafka.log.Log)
[2019-03-30 23:59:15,914] ERROR Error while deleting segments for response_topic-0 in dir /tmp/kafka-logs (kafka.server.LogDirFailureChannel)
java.nio.file.NoSuchFileException: /tmp/kafka-logs/response_topic-0/00000000000000000000.log
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:409)
	at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:262)
	at java.nio.file.Files.move(Files.java:1395)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:697)
	at org.apache.kafka.common.record.FileRecords.renameTo(FileRecords.java:212)
	at kafka.log.LogSegment.changeFileSuffixes(LogSegment.scala:415)
	at kafka.log.Log.kafka$log$Log$$asyncDeleteSegment(Log.scala:1601)
	at kafka.log.Log.kafka$log$Log$$deleteSegment(Log.scala:1588)
	at kafka.log.Log$$anonfun$deleteSegments$1$$anonfun$apply$mcI$sp$1.apply(Log.scala:1170)
	at kafka.log.Log$$anonfun$deleteSegments$1$$anonfun$apply$mcI$sp$1.apply(Log.scala:1170)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at kafka.log.Log$$anonfun$deleteSegments$1.apply$mcI$sp(Log.scala:1170)
	at kafka.log.Log$$anonfun$deleteSegments$1.apply(Log.scala:1161)
	at kafka.log.Log$$anonfun$deleteSegments$1.apply(Log.scala:1161)
	at kafka.log.Log.maybeHandleIOException(Log.scala:1678)
	at kafka.log.Log.deleteSegments(Log.scala:1161)
	at kafka.log.Log.deleteOldSegments(Log.scala:1156)
	at kafka.log.Log.deleteRetentionMsBreachedSegments(Log.scala:1228)
	at kafka.log.Log.deleteOldSegments(Log.scala:1222)
	at kafka.log.LogManager$$anonfun$cleanupLogs$3.apply(LogManager.scala:854)
	at kafka.log.LogManager$$anonfun$cleanupLogs$3.apply(LogManager.scala:852)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
	at kafka.log.LogManager.cleanupLogs(LogManager.scala:852)
	at kafka.log.LogManager$$anonfun$startup$1.apply$mcV$sp(LogManager.scala:385)
	at kafka.utils.KafkaScheduler$$anonfun$1.apply$mcV$sp(KafkaScheduler.scala:110)
	at kafka.utils.CoreUtils$$anon$1.run(CoreUtils.scala:62)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.nio.file.NoSuchFileException: /tmp/kafka-logs/response_topic-0/00000000000000000000.log -> /tmp/kafka-logs/response_topic-0/00000000000000000000.log.deleted
		at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
		at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
		at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:396)
		at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:262)
		at java.nio.file.Files.move(Files.java:1395)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:694)
		... 32 more
[2019-03-30 23:59:16,757] ERROR Uncaught exception in scheduled task 'kafka-log-retention' (kafka.utils.KafkaScheduler)
org.apache.kafka.common.errors.KafkaStorageException: Error while deleting segments for response_topic-0 in dir /tmp/kafka-logs
Caused by: java.nio.file.NoSuchFileException: /tmp/kafka-logs/response_topic-0/00000000000000000000.log
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:409)
	at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:262)
	at java.nio.file.Files.move(Files.java:1395)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:697)
	at org.apache.kafka.common.record.FileRecords.renameTo(FileRecords.java:212)
	at kafka.log.LogSegment.changeFileSuffixes(LogSegment.scala:415)
	at kafka.log.Log.kafka$log$Log$$asyncDeleteSegment(Log.scala:1601)
	at kafka.log.Log.kafka$log$Log$$deleteSegment(Log.scala:1588)
	at kafka.log.Log$$anonfun$deleteSegments$1$$anonfun$apply$mcI$sp$1.apply(Log.scala:1170)
	at kafka.log.Log$$anonfun$deleteSegments$1$$anonfun$apply$mcI$sp$1.apply(Log.scala:1170)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at kafka.log.Log$$anonfun$deleteSegments$1.apply$mcI$sp(Log.scala:1170)
	at kafka.log.Log$$anonfun$deleteSegments$1.apply(Log.scala:1161)
	at kafka.log.Log$$anonfun$deleteSegments$1.apply(Log.scala:1161)
	at kafka.log.Log.maybeHandleIOException(Log.scala:1678)
	at kafka.log.Log.deleteSegments(Log.scala:1161)
	at kafka.log.Log.deleteOldSegments(Log.scala:1156)
	at kafka.log.Log.deleteRetentionMsBreachedSegments(Log.scala:1228)
	at kafka.log.Log.deleteOldSegments(Log.scala:1222)
	at kafka.log.LogManager$$anonfun$cleanupLogs$3.apply(LogManager.scala:854)
	at kafka.log.LogManager$$anonfun$cleanupLogs$3.apply(LogManager.scala:852)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
	at kafka.log.LogManager.cleanupLogs(LogManager.scala:852)
	at kafka.log.LogManager$$anonfun$startup$1.apply$mcV$sp(LogManager.scala:385)
	at kafka.utils.KafkaScheduler$$anonfun$1.apply$mcV$sp(KafkaScheduler.scala:110)
	at kafka.utils.CoreUtils$$anon$1.run(CoreUtils.scala:62)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.nio.file.NoSuchFileException: /tmp/kafka-logs/response_topic-0/00000000000000000000.log -> /tmp/kafka-logs/response_topic-0/00000000000000000000.log.deleted
		at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
		at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
		at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:396)
		at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:262)
		at java.nio.file.Files.move(Files.java:1395)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:694)
		... 32 more
[2019-03-30 23:59:16,763] INFO [ReplicaManager broker=0] Stopping serving replicas in dir /tmp/kafka-logs (kafka.server.ReplicaManager)
[2019-03-30 23:59:16,863] INFO [ReplicaFetcherManager on broker 0] Removed fetcher for partitions response_topic-0,post_book-0 (kafka.server.ReplicaFetcherManager)
[2019-03-30 23:59:16,871] INFO [ReplicaAlterLogDirsManager on broker 0] Removed fetcher for partitions response_topic-0,post_book-0 (kafka.server.ReplicaAlterLogDirsManager)
[2019-03-30 23:59:16,978] INFO [ReplicaManager broker=0] Broker 0 stopped fetcher for partitions response_topic-0,post_book-0 and stopped moving logs for partitions  because they are in the failed log directory /tmp/kafka-logs. (kafka.server.ReplicaManager)
[2019-03-30 23:59:16,979] INFO Stopping serving logs in dir /tmp/kafka-logs (kafka.log.LogManager)
[2019-03-30 23:59:17,048] ERROR Shutdown broker because all log dirs in /tmp/kafka-logs have failed (kafka.log.LogManager)
